services:
  webapi:
    build: .
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - .venv
        - action: rebuild
          path: ./uv.lock
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  mongo:
    image: mongo:8.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb

volumes:
  mongo_data:
  mongo_config: