line-length = 120
indent-width = 4

[lint]
select = ["E", "W", "FAST", "N", "ASYNC", "I"]
ignore = ["E402"]
extend-safe-fixes = ["FAST", "E"]
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.pydocstyle]
convention = "google"
ignore-decorators = ["typing.overload"]

[lint.isort]
split-on-trailing-comma = false

[format]
quote-style = "single"
indent-style = "space"
line-ending = "auto"
skip-magic-trailing-comma = true
docstring-code-format = true
docstring-code-line-length = "dynamic"
